---
- name: Reboot RHEL system if required
  hosts: servers
  become: yes
  tasks:
    - name: Check for reboot flag file
      stat:
        path: /tmp/reboot.flag
      register: reboot_flag

    - name: Reboot the system if flag exists
      reboot:
        msg: "Rebooting after package update"
        connect_timeout: 5
        reboot_timeout: 900
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      when: reboot_flag.stat.exists

    - name: Remove reboot flag after reboot
      file:
        path: /tmp/reboot.flag
        state: absent
      when: reboot_flag.stat.exists
