---
- name: Red Hat Enterprise Linux 9.4 patch updates
  hosts: servers
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Update all packages except excluded ones
      dnf:
        name: "*"
        state: latest
        exclude: 
          - kernel*
          - kmod*
      register: update_result

    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      changed_when: false

    - name: Set reboot_required fact if needed
      set_fact:
        reboot_needed: true
      when: reboot_required.stat.exists

    - name: Write reboot trigger file for the next playbook
      copy:
        dest: /tmp/reboot.flag
        content: "reboot needed"
      when: reboot_needed | default(false)
